---
- name: Ensure EPEL and gcc are installed (Varnish dependency).
  yum: 
    name={{ item }}
    state=present
  with_items:
    - gcc
    - epel-release

- name: Add Varnish repository.
  command: >
    rpm --nosignature -i https://repo.varnish-cache.org/redhat/varnish-{{ varnish_version }}.el{{ ansible_distribution_major_version }}.rpm
    creates=/var/lib/yum/repos/x86_64/{{ ansible_distribution_major_version }}/varnish-{{ varnish_version }}
  ignore_errors: true

- name: Install Varnish.
  yum:
    name: varnish
    state: installed
    enablerepo: "varnish-{{ varnish_version }},epel"
    disablerepo: "*"

- name: Copy Varnish configuration (sysvinit).
  template:
    src: varnish.j2
    dest: /etc/sysconfig/varnish
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int < 7

- name: Copy Varnish configuration (systemd).
  template:
    src: varnish.params.j2
    dest: /etc/varnish/varnish.params
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 7
