---
- name: Ensure EPEL and gcc are installed (Varnish dependency).
  yum: 
    name={{ item }}
    state=present
  with_items:
    - gcc
    - epel-release

- name: Add Varnish repository.
  command: |
    curl -s https://packagecloud.io/install/repositories/varnishcache/varnish41/script.rpm.sh | bash
    creates=/etc/yum.repos.d/varnishcache_varnish41.repo
  ignore_errors: true

- name: Install Varnish.
  yum:
    name: varnish
    state: installed
    # enablerepo: "varnish-{{ varnish_version }},epel"
    # disablerepo: "*"

- name: Copy Varnish configuration (sysvinit).
  template:
    src: varnish.j2
    dest: /etc/sysconfig/varnish
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int < 7

- name: Copy Varnish configuration (systemd).
  template:
    src: varnish.params.j2
    dest: /etc/varnish/varnish.params
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 7

- name: Copy logrotate configuration for Varnish
  copy:
    src: logrotate.d/varnish
    dest: /etc/logrotate.d/varnish
    owner: root
    group: root
    mode: 0644
